# Generated by Django 4.2.10 on 2025-05-21 06:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=100, unique=True, verbose_name='Company Name')),
                ('company_alias', models.CharField(blank=True, max_length=100, null=True)),
                ('company_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
            ],
            options={
                'ordering': ['company_name'],
            },
        ),
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Unnamed', max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('inverter_capacity', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('efficiency_factor', models.FloatField(default=1.0)),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer_inverters', to='inverter.manufacturer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inverters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='PowerGeneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('measurement_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('energy_generated', models.DecimalField(decimal_places=3, help_text='Energy in kWh', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('inverter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_generation', to='inverter.inverter')),
            ],
            options={
                'ordering': ['-measurement_time'],
                'indexes': [models.Index(fields=['measurement_time'], name='inverter_po_measure_4db6dd_idx')],
                'unique_together': {('inverter', 'measurement_time')},
            },
        ),
        migrations.CreateModel(
            name='InverterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('voltage', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('current', models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('power', models.DecimalField(decimal_places=2, max_digits=10)),
                ('temperature', models.FloatField()),
                ('grid_connected', models.BooleanField(default=False)),
                ('inverter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='inverter.inverter')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inverter_data', to='inverter.manufacturer')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='inverter_in_timesta_698f27_idx'), models.Index(fields=['inverter', 'timestamp'], name='inverter_in_inverte_bcef19_idx')],
                'unique_together': {('inverter', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='Activation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activation_time', models.DateTimeField(auto_now_add=True, verbose_name='Activation Time')),
                ('inverter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='inverter.inverter', verbose_name='Inverter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'ordering': ['-activation_time'],
                'indexes': [models.Index(fields=['inverter', 'activation_time'], name='inverter_ac_inverte_a7d88f_idx')],
            },
        ),
    ]
