# Generated by Django 5.2.1 on 2025-05-21 09:56

import timescale.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inverter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='powergeneration',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='powergeneration',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='timestamp',
            field=timescale.db.models.fields.TimescaleDateTimeField(interval='1 day'),
        ),
        migrations.AlterField(
            model_name='powergeneration',
            name='measurement_time',
            field=timescale.db.models.fields.TimescaleDateTimeField(interval='1 day'),
        ),
    ]
