# Generated by Django 5.2.1 on 2025-06-04 06:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverter', '0002_remove_powergeneration_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='powergeneration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 4, 6, 23, 28, 935017, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='powergeneration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddIndex(
            model_name='powergeneration',
            index=models.Index(fields=['inverter', 'measurement_time'], name='inverter_po_inverte_b8cfcb_idx'),
        ),
    ]
