# Generated by Django 5.2.1 on 2025-06-10 06:55

import django.core.validators
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverter', '0003_powergeneration_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='powergeneration',
            name='avg_power',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average power in Watts', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='powergeneration',
            name='data_points_count',
            field=models.IntegerField(default=0, help_text='Number of data points used for calculation'),
        ),
        migrations.AlterField(
            model_name='powergeneration',
            name='measurement_time',
            field=timescale.db.models.fields.TimescaleDateTimeField(interval='1 hour'),
        ),
    ]
