# Generated by Django 5.2.1 on 2026-01-22 05:32

import django.core.validators
import django.db.models.deletion
import timescale.db.models.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverter', '0004_powergeneration_avg_power_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activation',
            options={'ordering': ['-activation_time'], 'verbose_name': 'Activation', 'verbose_name_plural': 'Activations'},
        ),
        migrations.AlterModelOptions(
            name='inverter',
            options={'ordering': ['-created_at'], 'verbose_name': 'Inverter', 'verbose_name_plural': 'Inverters'},
        ),
        migrations.AlterModelOptions(
            name='inverterdata',
            options={'ordering': ['-timestamp'], 'verbose_name': 'Inverter Data Point', 'verbose_name_plural': 'Inverter Data Points'},
        ),
        migrations.AlterModelOptions(
            name='manufacturer',
            options={'ordering': ['company_name'], 'verbose_name': 'Manufacturer', 'verbose_name_plural': 'Manufacturers'},
        ),
        migrations.AlterModelOptions(
            name='powergeneration',
            options={'ordering': ['-measurement_time'], 'verbose_name': 'Power Generation', 'verbose_name_plural': 'Power Generation Records'},
        ),
        migrations.AlterUniqueTogether(
            name='inverter',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inverter',
            name='model',
            field=models.CharField(blank=True, help_text='Manufacturer model number or identifier', max_length=100, null=True, verbose_name='Model'),
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Website'),
        ),
        migrations.AlterField(
            model_name='activation',
            name='user',
            field=models.ForeignKey(help_text='User who activated this inverter (for audit trail)', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='address',
            field=models.CharField(blank=True, help_text='Street address (optional for auto-created inverters)', max_length=100, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='city',
            field=models.CharField(blank=True, help_text='City name (optional for auto-created inverters)', max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='country',
            field=models.CharField(blank=True, help_text='Country name (optional for auto-created inverters)', max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='efficiency_factor',
            field=models.DecimalField(decimal_places=4, default=1.0, help_text='Efficiency factor (0.0 to 1.0, where 1.0 = 100% efficiency)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Efficiency Factor'),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='installation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Installation Date'),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='inverter_capacity',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum capacity in Watts', max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Capacity (W)'),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='latitude',
            field=models.FloatField(blank=True, help_text='GPS latitude coordinate (-90 to 90)', null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='longitude',
            field=models.FloatField(blank=True, help_text='GPS longitude coordinate (-180 to 180)', null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manufacturer_inverters', to='inverter.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='name',
            field=models.CharField(default='Unnamed', help_text='Human-readable name for the inverter', max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='serial_number',
            field=models.CharField(help_text='Unique serial number of the inverter', max_length=50, unique=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='state',
            field=models.CharField(blank=True, help_text='State or province (optional for auto-created inverters)', max_length=100, null=True, verbose_name='State/Province'),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='user',
            field=models.ForeignKey(blank=True, help_text='Owner of the inverter. Can be None for system-generated inverters.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_inverters', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='current',
            field=models.DecimalField(decimal_places=2, help_text='Current reading in Amperes', max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Current (A)'),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='grid_connected',
            field=models.BooleanField(default=False, help_text='Whether inverter is connected to the electrical grid', verbose_name='Grid Connected'),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='inverter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='inverter.inverter', verbose_name='Inverter'),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='manufacturer',
            field=models.ForeignKey(blank=True, help_text='Cached manufacturer reference for query performance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inverter_data', to='inverter.manufacturer', verbose_name='Manufacturer'),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='power',
            field=models.DecimalField(decimal_places=2, help_text='Calculated power (voltage * current) in Watts', max_digits=10, verbose_name='Power (W)'),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='temperature',
            field=models.FloatField(help_text='Temperature reading in Celsius', verbose_name='Temperature (°C)'),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='timestamp',
            field=timescale.db.models.fields.TimescaleDateTimeField(help_text='When this reading was taken', interval='1 day', verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='voltage',
            field=models.DecimalField(decimal_places=2, help_text='Voltage reading in Volts', max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Voltage (V)'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='company_alias',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Company Alias'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='gst_number',
            field=models.CharField(blank=True, help_text='15-character GST registration number', max_length=15, null=True, unique=True, verbose_name='GST Number'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='powergeneration',
            name='avg_power',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Average power output in Watts during this hour', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Average Power (W)'),
        ),
        migrations.AlterField(
            model_name='powergeneration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='powergeneration',
            name='data_points_count',
            field=models.IntegerField(default=0, help_text='Number of InverterData points used for this calculation', verbose_name='Data Points Count'),
        ),
        migrations.AlterField(
            model_name='powergeneration',
            name='energy_generated',
            field=models.DecimalField(decimal_places=3, help_text='Total energy generated in kWh during this hour', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Energy Generated (kWh)'),
        ),
        migrations.AlterField(
            model_name='powergeneration',
            name='inverter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_generation', to='inverter.inverter', verbose_name='Inverter'),
        ),
        migrations.AlterField(
            model_name='powergeneration',
            name='measurement_time',
            field=timescale.db.models.fields.TimescaleDateTimeField(help_text='Start of the hour period for this aggregation', interval='1 hour', verbose_name='Measurement Time'),
        ),
        migrations.AlterField(
            model_name='powergeneration',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AddIndex(
            model_name='activation',
            index=models.Index(fields=['user', 'activation_time'], name='inverter_ac_user_id_b9c7d1_idx'),
        ),
        migrations.AddIndex(
            model_name='inverter',
            index=models.Index(fields=['serial_number'], name='inverter_in_serial__193e02_idx'),
        ),
        migrations.AddIndex(
            model_name='inverter',
            index=models.Index(fields=['user', 'created_at'], name='inverter_in_user_id_5186a2_idx'),
        ),
        migrations.AddIndex(
            model_name='inverter',
            index=models.Index(fields=['manufacturer'], name='inverter_in_manufac_063753_idx'),
        ),
        migrations.AddIndex(
            model_name='inverterdata',
            index=models.Index(fields=['grid_connected', 'timestamp'], name='inverter_in_grid_co_1162dc_idx'),
        ),
        migrations.AddIndex(
            model_name='powergeneration',
            index=models.Index(fields=['inverter', '-measurement_time'], name='inverter_po_inverte_4264fc_idx'),
        ),
    ]
