# Generated by Django 5.2.1 on 2026-01-22 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverter', '0005_alter_activation_options_alter_inverter_options_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='inverterdata',
            name='inverter_in_grid_co_1162dc_idx',
        ),
        migrations.RemoveField(
            model_name='inverterdata',
            name='manufacturer',
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='timestamp',
            field=models.DateTimeField(db_index=True, help_text='When this reading was taken', verbose_name='Timestamp'),
        ),
        migrations.AlterField(
            model_name='powergeneration',
            name='measurement_time',
            field=models.DateTimeField(db_index=True, help_text='Start of the hour period for this aggregation', verbose_name='Measurement Time'),
        ),
        migrations.AddIndex(
            model_name='inverterdata',
            index=models.Index(fields=['inverter', '-timestamp'], name='inverter_in_inverte_7aacd4_idx'),
        ),
    ]
