# Generated by Django 5.2.1 on 2026-01-23 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverter', '0006_remove_inverterdata_inverter_in_grid_co_1162dc_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='inverter',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inverters', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
