# Generated by Django 5.2.1 on 2026-01-28 06:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverter', '0007_alter_inverter_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inverterdata',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='current',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='grid_connected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='inverter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_points', to='inverter.inverter'),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='power',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='temperature',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='timestamp',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='inverterdata',
            name='voltage',
            field=models.DecimalField(decimal_places=2, max_digits=7, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
