# Generated by Django 5.2.1 on 2026-04-29 09:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inverter', '0008_alter_inverterdata_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inverterdata',
            name='ipv',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='PV current (DC side)', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='inverterdata',
            name='vpv',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='PV voltage (DC side)', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
